name: Setup Turborepo environment

description: Setup Turborepo environment

inputs:
  turbo-token:
    description: Turborepo token for remote caching
    required: true
  turbo-team:
    description: Turborepo team name for remote caching
    required: true

runs:
  using: composite
  steps:
    - name: Set remote caching environment variables
      shell: bash
      run: |
        echo "TURBO_TOKEN=${{ inputs.turbo-token }}" >> "$GITHUB_ENV"
        echo "TURBO_TEAM=${{ inputs.turbo-team }}" >> "$GITHUB_ENV"

    - name: Set TURBO_SCM_BASE
      shell: bash
      run: echo "TURBO_SCM_BASE=${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}" >> "$GITHUB_ENV"
