FROM node:22-alpine

WORKDIR /app

# Disable Husky in container
ENV HUSKY=0

RUN npm i -g corepack@latest

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./

RUN corepack enable pnpm

RUN pnpm install

COPY . .

EXPOSE 3000

CMD ["pnpm", "--filter", "@repo/api", "dev"]
