services:
  riven:
    extends:
      file: ./apps/riven/docker-compose.yaml
      service: riven
    develop:
      watch:
        - path: apps
          action: sync
          target: /riven/apps
        - path: packages
          action: sync
          target: /riven/packages
        - path: pnpm-lock.yaml
          action: sync+exec
          target: /riven/pnpm-lock.yaml
          exec:
            command: pnpm install
    profiles:
      - all

  riven-db:
    extends:
      file: ./apps/riven/docker-compose.yaml
      service: riven-db
    profiles:
      - all
      - services
      - analytics

  riven-cache:
    extends:
      file: ./apps/riven/docker-compose.yaml
      service: riven-cache
    profiles:
      - all
      - services
      - analytics

  bullboard:
    container_name: bullboard
    image: venatum/bull-board
    restart: unless-stopped
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      REDIS_HOST: riven-cache
    profiles:
      - all
      - analytics
    depends_on:
      - riven-cache

  plex:
    extends:
      file: ./packages/plugin-plex/docker-compose.yaml
      service: plex
    profiles:
      - all
      - services

  spotlight:
    container_name: spotlight
    image: ghcr.io/getsentry/spotlight:latest
    restart: unless-stopped
    ports:
      - 8969:8969
    profiles:
      - all
      - analytics

  seerr:
    extends:
      file: ./packages/plugin-seerr/docker-compose.yaml
      service: seerr
    profiles:
      - all
      - services

  stremthru:
    extends:
      file: ./packages/plugin-stremthru/docker-compose.yaml
      service: stremthru
    profiles:
      - all
      - services

volumes:
  riven-db:
