packages:
  - apps/*
  - packages/*
  - packages/core/*
  - packages/listrr/*

catalog:
  "@apollo/datasource-rest": ^6.4.1
  "@kubb/cli": ^4.11.1
  "@kubb/core": ^4.11.1
  "@kubb/plugin-oas": ^4.11.1
  "@kubb/plugin-zod": ^4.11.1
  "@types/jest": 30.0.0
  "@types/node": ^22
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  "@typescript-eslint/parser": ^8.49.0
  class-validator: ^0.14.3
  eslint: ^9.39.2
  jest: ^30
  jiti: 2.6.1
  next: ^16.0.10
  pg: ^8.16.3
  react: ^19.2.3
  react-dom: ^19.2.3
  reflect-metadata: ^0.2.2
  typeorm: ^0.3.28
  typescript: ^5.9.3
  zod: 4.1.13

configDependencies:
  "@pnpm/plugin-better-defaults": 0.2.1+sha512-3Fmur80S7+vmOKMmTdKS6JofiuvpUaBIdKEpgDyr9571FHo5Z4O2nrRUaSflxvwEakeYxIaFZ5MBaqAUnYHaeg==

injectWorkspacePackages: true

linkWorkspacePackages: true
