packages:
  - apps/*
  - packages/*
  - packages/core/*
  - packages/listrr/*
  - packages/mdblist/*

catalog:
  "@apollo/datasource-rest": 6.4.1
  "@faker-js/faker": 10.1.0
  "@kubb/cli": 4.11.1
  "@kubb/core": 4.11.1
  "@kubb/plugin-faker": ^4.11.1
  "@kubb/plugin-msw": ^4.11.1
  "@kubb/plugin-oas": 4.11.1
  "@kubb/plugin-ts": ^4.11.1
  "@kubb/plugin-zod": 4.11.1
  "@types/node": ^24.0.0
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  "@typescript-eslint/parser": ^8.49.0
  "@vitest/coverage-v8": 4.0.15
  class-validator: 0.14.3
  eslint: ^9.39.2
  graphql: ^16.12.0
  jiti: 2.6.1
  msw: 2.12.4
  next: ^16.0.10
  pg: ^8.16.3
  react: ^19.2.3
  react-dom: ^19.2.3
  reflect-metadata: 0.2.2
  type-graphql: 2.0.0-rc.2
  typeorm: ^0.3.28
  typescript: ^5.9.3
  undici: ^7.16.0
  vitest: 4.0.15
  zod: 4.1.13

configDependencies:
  "@pnpm/plugin-better-defaults": 0.2.1+sha512-3Fmur80S7+vmOKMmTdKS6JofiuvpUaBIdKEpgDyr9571FHo5Z4O2nrRUaSflxvwEakeYxIaFZ5MBaqAUnYHaeg==

linkWorkspacePackages: true

publicHoistPattern:
  - "*vitest*"
  - vite-node
