packages:
  - apps/*
  - packages/*
  - packages/core/*

catalog:
  "@apollo/datasource-rest": 6.4.1
  "@apollo/server": 5.2.0
  "@apollo/utils.keyvadapter": ^4.0.1
  "@apollo/utils.keyvaluecache": ^4.0.0
  "@faker-js/faker": 10.1.0
  "@kubb/cli": 4.20.1
  "@kubb/core": 4.20.1
  "@kubb/plugin-faker": 4.20.1
  "@kubb/plugin-msw": 4.20.1
  "@kubb/plugin-oas": 4.20.1
  "@kubb/plugin-ts": 4.20.1
  "@kubb/plugin-zod": 4.20.1
  "@mikro-orm/core": ^6.6.4
  "@mikro-orm/postgresql": ^6.6.4
  "@mikro-orm/reflection": ^6.6.4
  "@opentelemetry/context-async-hooks": ^2.2.0
  "@opentelemetry/exporter-metrics-otlp-proto": ^0.208.0
  "@opentelemetry/exporter-trace-otlp-proto": ^0.208.0
  "@opentelemetry/sdk-metrics": ^2.2.0
  "@opentelemetry/sdk-node": ^0.208.0
  "@types/luxon": ^3.7.1
  "@types/node": ^24.0.0
  "@typescript-eslint/parser": ^8.49.0
  "@vitest/coverage-v8": 4.0.15
  bullmq: 5.66.4
  bullmq-otel: ^1.1.0
  class-validator: 0.14.3
  es-toolkit: ^1.44.0
  eslint: ^9.39.2
  graphql: 16.12.0
  graphql-tag: ^2.12.6
  jiti: 2.6.1
  limiter: 3.0.0
  luxon: ^3.7.2
  msw: 2.12.4
  reflect-metadata: 0.2.2
  type-graphql: 2.0.0-rc.2
  typescript: ^5.9.3
  undici: ^7.18.2
  vitest: 4.0.15
  winston: ^3.19.0
  xstate: ^5.25.0
  zod: 4.1.13
  zod2md: ^0.2.5

cleanupUnusedCatalogs: true

configDependencies:
  "@pnpm/plugin-better-defaults": 0.2.1+sha512-3Fmur80S7+vmOKMmTdKS6JofiuvpUaBIdKEpgDyr9571FHo5Z4O2nrRUaSflxvwEakeYxIaFZ5MBaqAUnYHaeg==

ignoredBuiltDependencies:
  - redis-memory-server

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@apollo/protobufjs"
  - "@parcel/watcher"
  - "@swc/core"
  - "@zkochan/fuse-native"
  - core-js-pure
  - cpu-features
  - es5-ext
  - esbuild
  - msgpackr-extract
  - msw
  - protobufjs
  - sqlite3
  - ssh2
  - unrs-resolver

packageExtensions:
  "@opentelemetry/sdk-node":
    dependencies:
      "@opentelemetry/context-async-hooks": ^2.0.0
  "@zkochan/fuse-native@*":
    dependencies:
      node-gyp: ^12.0.0
  bullmq-otel:
    dependencies:
      tslib: ^2.0.0

publicHoistPattern:
  - "*vitest*"
  - vite-node
