projects:
  default:
    schema:
      - ../riven/schema.graphql
      - ./.$houdini/graphql/schema.graphql
    documents:
      - "**/*.gql"
      - "**/*.svelte"
      - ./.$houdini/graphql/documents.gql
