import type { CodegenConfig } from "@graphql-codegen/cli";
import type { TypeScriptPluginConfig } from "@graphql-codegen/typescript";
import type { TypeScriptDocumentsPluginConfig } from "@graphql-codegen/typescript-operations";

export default {
  schema: "../riven/schema.graphql",
  documents: ["app/**/*.ts", "app/**/*.tsx", "!app/**/__generated__/**/*"],
  ignoreNoDocuments: true,
  overwrite: true,
  importExtension: ".ts",
  generates: {
    "./app/_types/__generated__/graphql.ts": {
      plugins: ["typescript"],
      config: {
        enumsAsTypes: true,
      } satisfies TypeScriptPluginConfig,
    },
    "./app/": {
      preset: "near-operation-file",
      presetConfig: {
        // This should be the file generated by the "typescript" plugin above,
        // relative to the directory specified for this configuration
        baseTypesPath: "./_types/__generated__/graphql.ts",
        extension: ".typegen.ts",
      },
      plugins: ["typescript-operations"],
      // Note: these config options moved from the other generated file config
      config: {
        scalars: {
          ID: "`${string}-${string}-${string}-${string}-${string}`",
          BigInt: "number",
          DateTimeISO: "string",
          JSONObject: "Record<string, unknown>",
        },
        strictScalars: true,
        avoidOptionals: {
          // Use `null` for nullable fields instead of optionals
          field: true,
          // Allow nullable input fields to remain unspecified
          inputValue: false,
        },
        // Apollo Client always includes `__typename` fields
        nonOptionalTypename: true,
        // Apollo Client doesn't add the `__typename` field to root types so
        // don't generate a type for the `__typename` for root operation types.
        skipTypeNameForRoot: true,
        // Use string values for enums (e.g. 'one' | 'two')
        allowEnumStringTypes: true,
        inlineFragmentTypes: "mask",
        customDirectives: {
          apolloUnmask: true,
        },
      } satisfies TypeScriptDocumentsPluginConfig,
    },
  },
} satisfies CodegenConfig;
