import { type Handler, transforms } from "@viren070/parse-torrent-title";

const keywords = new Set([
  "10musume",
  "18eighteen",
  "18vr",
  "1pondo",
  "21naturals",
  "21sextury",
  "5kporn",
  "5kteens",
  "abbiemaley",
  "abbywinters",
  "abuseme",
  "accidentalgangbang",
  "activeduty",
  "adulttime",
  "alexlegend",
  "allanal",
  "allanalallthetime",
  "allblackx",
  "allgirlmassage",
  "allherluv",
  "allinternal",
  "alsscan",
  "alterotic",
  "amateurallure",
  "amateurboxxx",
  "amourangels",
  "anal",
  "anal-angels",
  "anal-beauty",
  "anal4k",
  "analized",
  "analmom",
  "analonly",
  "analoverdose",
  "analteenangels",
  "analtherapyxxx",
  "analvids",
  "andolinixxl",
  "anidb",
  "anilos",
  "apovstory",
  "archangelvideo",
  "ashemaletube",
  "asiansexdiary",
  "assholefever",
  "asstraffic",
  "assy",
  "assylum",
  "atkexotics",
  "atkgirlfriends",
  "atkhairy",
  "auntjudys",
  "auntjudysxxx",
  "babes",
  "babevr",
  "backroomcastingcouch",
  "baddaddypov",
  "badfamilypov",
  "badmilfs",
  "badmommypov",
  "badoinkvr",
  "badteenspunished",
  "baeb",
  "bangbros",
  "bangingbeauties",
  "barelylegal",
  "bbcparadise",
  "bbcpie",
  "bbcsurprise",
  "beauty-angels",
  "beauty4k",
  "belamionline",
  "bellesafilms",
  "bellesahouse",
  "bffs",
  "bigbootytgirls",
  "biggulpgirls",
  "billiestar",
  "bjraw",
  "blackambush",
  "blacked",
  "blackedraw",
  "blacksonblondes",
  "boygusher",
  "bradmontana",
  "brandnewamateurs",
  "brasilvr",
  "brattymilf",
  "brattysis",
  "brazzers",
  "breeditraw",
  "bride4k",
  "brokenlatinawhores",
  "brokensluts",
  "brookelynnebriar",
  "bryci",
  "burningangel",
  "buttman",
  "cadinot",
  "camwhores",
  "caribbeancom",
  "castingcouch-x",
  "chaosmen",
  "cheatingsis",
  "cherrypimps",
  "chloelamour",
  "citebeur",
  "clips4sale",
  "clubseventeen",
  "clubsweethearts",
  "clubtug",
  "cockyboys",
  "colbyknox",
  "college-uniform",
  "creampie-angels",
  "cuckhunter",
  "cuckoldsessions",
  "cum4k",
  "cumswappingsis",
  "czechescortgirls",
  "czechharem",
  "czechsexcasting",
  "czechvr",
  "czechvrcasting",
  "czechvrfetish",
  "dadcrush",
  "daddy4k",
  "danejones",
  "danidaniels",
  "danni",
  "darkroomvr",
  "darkx",
  "datingmystepson",
  "daughterswap",
  "ddfbusty",
  "debt4k",
  "deeplush",
  "deepthroatsirens",
  "defloration",
  "desperateamateurs",
  "devilsfilm",
  "devilstgirls",
  "dickdrainers",
  "digitaldesire",
  "digitalplayground",
  "dirtyauditions",
  "doghousedigital",
  "dorcelclub",
  "dpfanatics",
  "dreamtranny",
  "dtfsluts",
  "elegantangel",
  "ericvideos",
  "erito",
  "eroticax",
  "eternaldesire",
  "eurocreme",
  "evilangel",
  "evolvedfights",
  "evolvedfightslez",
  "excogigirls",
  "exotic4k",
  "exploitedcollegegirls",
  "exxxtrasmall",
  "facials4k",
  "fakehostel",
  "faketaxi",
  "familyhookups",
  "familysinners",
  "familystrokes",
  "familyswap",
  "familytherapyxxx",
  "familyxxx",
  "fantasyhd",
  "femdomempire",
  "femjoy",
  "filthyfamily",
  "finishhim",
  "firstanalquest",
  "firstbgg",
  "firstclasspov",
  "fistertwister",
  "fit18",
  "fitting-room",
  "foxxedup",
  "freeusefantasy",
  "freeusemilf",
  "frolicme",
  "fuckedhard18",
  "fuckermate",
  "fuckingawesome",
  "fuckstudies",
  "futanari",
  "gag-n-gape",
  "gangbangcreampie",
  "gaycest",
  "genderxfilms",
  "girlcum",
  "girlfriendsfilms",
  "girlgirlxxx",
  "girlsgotcream",
  "girlsonlyporn",
  "girlsoutwest",
  "girlsunderarrest",
  "girlsway",
  "givemepink",
  "gloryhole",
  "gloryholeinitiations",
  "gloryholesecrets",
  "gloryholeswallow",
  "gotfilled",
  "grooby",
  "groobyvr",
  "handsonhardcore",
  "hardx",
  "hdmassageporn",
  "hdsex18",
  "heavyonhotties",
  "hegre",
  "hegre-art",
  "helixstudios",
  "hentaied",
  "heyzo",
  "hijabhookup",
  "hijabmylfs",
  "hobybuchanon",
  "holed",
  "hookuphotshot",
  "hornyhousehold",
  "horrorporn",
  "hotguysfuck",
  "hotmilfsfuck",
  "hotwifexxx",
  "houseoftaboo",
  "hucows",
  "hunt4k",
  "hussiepass",
  "ifeelmyself",
  "ignore4k",
  "ikillitts",
  "iknowthatgirl",
  "immorallive",
  "imnotyourmommy",
  "innocenthigh",
  "interracialblowbang",
  "intimatepov",
  "itspov",
  "jacquieetmicheltv",
  "japanhdv",
  "jav",
  "jayspov",
  "joibabes",
  "joymii",
  "julesjordan",
  "karups",
  "katiebanks",
  "kellymadison",
  "kin8tengoku",
  "kinkvr",
  "kinkyfamily",
  "kinkyspa",
  "kristenbjorn",
  "ladyboy",
  "lesbea",
  "lethalhardcorevr",
  "letsdoeit",
  "lezcuties",
  "lifeselector",
  "lilhumpers",
  "littleasians",
  "littlecaprice-dreams",
  "loan4k",
  "lookathernow",
  "loveherboobs",
  "loveherfeet",
  "lubed",
  "lucasentertainment",
  "lustery",
  "lustreality",
  "manojob",
  "manuelferrara",
  "manyvids",
  "mariskax",
  "mature4k",
  "maturegapers",
  "maxinex",
  "metart",
  "metartx",
  "milfed",
  "milfthing",
  "milfvr",
  "missax",
  "moderndaysins",
  "mofos",
  "momcomesfirst",
  "momlover",
  "mommyblowsbest",
  "mommygotboobs",
  "mommysboy",
  "mommysgirl",
  "momsbangteens",
  "momsboytoy",
  "momsfamilysecrets",
  "momslickteens",
  "momsteachsex",
  "momstight",
  "momswap",
  "momswapped",
  "momwantscreampie",
  "momwantstobreed",
  "momxxx",
  "monstercub",
  "motherless",
  "mrbigfatdick",
  "mrluckypov",
  "muses",
  "mybabysittersclub",
  "mydirtyhobby",
  "myfamilypies",
  "mylf",
  "mylfdom",
  "mylifeinmiami",
  "mypervyfamily",
  "mysweetapple",
  "nakedsword",
  "naughtyamerica",
  "naughtyamericavr",
  "netvideogirls",
  "newsensations",
  "nextdoorbuddies",
  "nextdoorraw",
  "nextdoortwink",
  "nfbusty",
  "noboring",
  "nubilefilms",
  "nubiles",
  "nubiles-casting",
  "nubiles-porn",
  "nubilesporn",
  "nurumassage",
  "nympho",
  "ohmyholes",
  "old-n-young",
  "oldgoesyoung",
  "oldje",
  "oldje-3some",
  "onlyfans",
  "onlytarts",
  "onlyteenblowjobs",
  "oopsie",
  "over40handjobs",
  "parasited",
  "passion-hd",
  "pegasproductions",
  "penthousegold",
  "perfectgirlfriend",
  "pervcity",
  "pervdoctor",
  "perversefamily",
  "pervmom",
  "pervnana",
  "pervtherapy",
  "petitehdporn",
  "pie4k",
  "pinupfiles",
  "pissplay",
  "pjgirls",
  "playboy",
  "playboyplus",
  "plumperpass",
  "pornbox",
  "porncornvr",
  "porndudecasting",
  "pornfidelity",
  "pornforce",
  "pornhub",
  "pornhubpremium",
  "pornmegaload",
  "pornworld",
  "povd",
  "povmasters",
  "povr",
  "prettydirty",
  "princesscum",
  "private",
  "producersfun",
  "profiles",
  "propertysex",
  "publicagent",
  "publicsexadventures",
  "pure-ts",
  "puremature",
  "puretaboo",
  "putalocura",
  "r18",
  "rawattack",
  "rawcouples",
  "rawfuck",
  "realityjunkies",
  "realitykings",
  "realitylovers",
  "realjamvr",
  "realtimebondage",
  "reddit",
  "rickysroom",
  "riggsfilms",
  "rim4k",
  "roccosiffredi",
  "romemajor",
  "sapphicerotica",
  "sayuncle",
  "scoutboys",
  "seancody",
  "seehimfuck",
  "sexart",
  "sexbabesvr",
  "sexintaxi",
  "sexlikereal",
  "sexmex",
  "sexselector",
  "sexuallybroken",
  "sexwithmuslims",
  "shame4k",
  "shelovesblack",
  "sheseducedme",
  "shewillcheat",
  "shoplyfter",
  "shoplyftermylf",
  "showybeauty",
  "sislovesme",
  "sisswap",
  "slayed",
  "slr",
  "slroriginals",
  "slutinspection",
  "smashed",
  "sofiemariexxx",
  "soloteengirls",
  "spankmonster",
  "spermmania",
  "spizoo",
  "spyfam",
  "stasyq",
  "stasyqvr",
  "staxus",
  "stayhomepov",
  "stepsiblingscaught",
  "stockydudes",
  "straplez",
  "streaming",
  "stripzvr",
  "stunning18",
  "swallowbay",
  "swallowed",
  "swallowsalon",
  "sweetheartvideo",
  "sweetsinner",
  "tabooheat",
  "tadpolexstudio",
  "teamskeet",
  "teasepov",
  "teencurves",
  "teenfidelity",
  "teenmegaworld",
  "teenpies",
  "teensexmania",
  "teensexmovs",
  "teensloveanal",
  "teensloveblackcocks",
  "teenslovehugecocks",
  "teensneaks",
  "teenstryblacks",
  "teenytaboo",
  "theartporn",
  "theflourishxxx",
  "thehabibshow",
  "thelifeerotic",
  "threesomes",
  "throated",
  "timtales",
  "tiny4k",
  "tmwpov",
  "tmwvrnet",
  "tonightsgirlfriend",
  "topwebmodels",
  "touchmywife",
  "toughlovex",
  "transangels",
  "transatplay",
  "transfixed",
  "transsensual",
  "tranzvr",
  "trickymasseur",
  "tripforfuck",
  "trueamateurs",
  "trueanal",
  "truelesbian",
  "tsplayground",
  "tspov",
  "tsraw",
  "tushy",
  "tushyraw",
  "twinks",
  "twistys",
  "twotgirls",
  "ultrafilms",
  "valentina",
  "vickyathome",
  "vipissy",
  "virtualporn",
  "virtualrealamateurporn",
  "virtualrealpassion",
  "virtualrealporn",
  "virtualrealtrans",
  "virtualtaboo",
  "vivid",
  "vivthomas",
  "vrbangers",
  "vrbtrans",
  "vrconk",
  "vrcosplayx",
  "vrhush",
  "vrintimacy",
  "vrlatina",
  "vrporn",
  "wakeupnfuck",
  "wankitnow",
  "wankz",
  "wankzvr",
  "watch4beauty",
  "webyoung",
  "wefuckblackgirls",
  "welivetogether",
  "wetandpissy",
  "wetandpuffy",
  "wetvr",
  "whiteteensblackcocks",
  "wildoncam",
  "willtilexxx",
  "woodmancastingx",
  "wowgirls",
  "wowporn",
  "x-angels",
  "x-art",
  "xart",
  "xevunleashed",
  "xsinsvr",
  "xtube",
  "xvideos",
  "xvirtual",
  "xxxjobinterviews",
  "xxxpawn",
  "yanks",
  "yesgirlz",
  "youngermommy",
  "accidental creampie",
  "aletta ocean",
  "alexis love",
  "alexis texas",
  "amateur allure",
  "amateur blowjob",
  "amateur gangbang",
  "amateur porn",
  "amateur sex",
  "amateur teen",
  "amateur threesome",
  "amber rayne",
  "anal amateur",
  "anal asian",
  "anal blonde",
  "anal bondage",
  "anal casting",
  "anal cream",
  "anal creampie",
  "anal destruction",
  "anal fingering",
  "anal fisting",
  "anal fuck",
  "anal fucking",
  "anal gangbang",
  "anal gape",
  "anal hardcore",
  "anal massage",
  "anal milf",
  "anal orgasm",
  "anal orgy",
  "anal party",
  "anal pov",
  "anal punishment",
  "anal queen",
  "anal sex",
  "anal squirt",
  "anal surprise",
  "anal teen",
  "anal teens",
  "anal threesome",
  "anal training",
  "anal video",
  "anal virgin",
  "angel dark",
  "angel eyes",
  "animated porn",
  "anita dark",
  "ann marie",
  "annette schwarz",
  "asa akira",
  "asian amateur",
  "asian anal",
  "asian massage",
  "asian milf",
  "asian sex",
  "asian teen",
  "ass fuck",
  "ass licking",
  "ass to mouth",
  "ass xxx",
  "audrey bitoni",
  "audrey hollander",
  "avy scott",
  "babysitter sex",
  "bang bus",
  "beach sex",
  "beautiful ass",
  "beautiful pussy",
  "beautiful tits",
  "behind the scenes",
  "best blowjob",
  "best blowjob ever",
  "big ass",
  "big black cock",
  "big black dick",
  "big boobs",
  "big booty",
  "big butts",
  "big cock",
  "big cocks",
  "big dick",
  "big dicks",
  "big natural tits",
  "big tit",
  "big tits",
  "big tits milf",
  "big titties",
  "bisexual threesome",
  "black anal",
  "black booty",
  "black cock",
  "black dick",
  "black girl",
  "black pussy",
  "black tits",
  "blow job",
  "blow jobs",
  "blowjob compilation",
  "blue angel",
  "bobbi starr",
  "bree olsen",
  "briana banks",
  "brianna beach",
  "britney spears",
  "brittany andrews",
  "broke straight boys",
  "brooke banner",
  "brother and sister",
  "bubble butt",
  "busty milf",
  "busty teen",
  "butt fuck",
  "carmella bing",
  "casting couch",
  "caught masturbating",
  "celebrity sex tape",
  "charley chase",
  "charlotte stokely",
  "cheating wife",
  "christy canyon",
  "cock hero",
  "cock sucking",
  "college girls",
  "creampie compilation",
  "creampie gangbang",
  "crissy moran",
  "crystal clear",
  "cuckold creampie",
  "cum compilation",
  "cum in mouth",
  "cum inside",
  "cum shots",
  "cum swallow",
  "cum swap",
  "cum twice",
  "cumshot compilation",
  "cute teen",
  "dana dearmond",
  "dancing bear",
  "deep anal",
  "deep throat",
  "deepthroat blowjob",
  "devon lee",
  "dirty anal",
  "dirty masseur",
  "dirty talk",
  "double anal",
  "double creampie",
  "double dick",
  "double dildo",
  "double fisting",
  "double fuck",
  "double penetration",
  "double vaginal",
  "drunk sex",
  "eating cum",
  "eating pussy",
  "ebony ass",
  "ebony gangbang",
  "ebony teen",
  "elena grimaldi",
  "ellen saint",
  "enormous cock",
  "erotic massage",
  "evil angel",
  "ex girlfriend",
  "exploited college",
  "exploited college girls",
  "extreme anal",
  "extreme deepthroat",
  "extreme fisting",
  "facial cumshot",
  "fat cock",
  "faye reagan",
  "first anal",
  "first time",
  "first time anal",
  "fist each others",
  "fisting anal",
  "foot fetish",
  "francesca le",
  "free movies",
  "french milf",
  "french porn",
  "french sex",
  "friends hot mom",
  "friends mom",
  "fuck for money",
  "fuck machine",
  "fuck me",
  "fuck me hard",
  "fuck my ass",
  "fuck my pussy",
  "fucked from behind",
  "fucked hard",
  "fucking ass",
  "fucking hard",
  "fucking machine",
  "full movie",
  "gang bang",
  "gangbang creampie",
  "german sex",
  "gf revenge",
  "girl cum",
  "girl on girl",
  "girls cumming",
  "girls do porn",
  "girls gone wild",
  "girls with big tits",
  "glory hole",
  "good pussy",
  "group sex",
  "hairy pussy",
  "hand domination",
  "hand job",
  "hard cock",
  "hard fuck",
  "hardcore fucking",
  "harmony rose",
  "hidden camera",
  "hitomi tanaka",
  "horny girl",
  "horny milf",
  "horny wife",
  "hot asian",
  "hot ass",
  "hot blonde",
  "hot blondes",
  "hot brunette",
  "hot fuck",
  "hot latina",
  "hot milfs",
  "hot mom",
  "hot sex",
  "how to fuck",
  "huge ass",
  "huge boobs",
  "huge cock",
  "huge dick",
  "huge dildo",
  "huge tits",
  "i have a wife",
  "in the ass",
  "inari vachs",
  "interracial anal",
  "interracial dp",
  "interracial milf",
  "interracial threesome",
  "isis love",
  "isis taylor",
  "italian anal",
  "italian milf",
  "italian sex",
  "jana cova",
  "japanese amateur",
  "japanese creampie",
  "japanese mom",
  "japanese teacher",
  "jayden jaymes",
  "jenaveve jolie",
  "jenna haze",
  "jerk off",
  "jerk off instruction",
  "jerking off",
  "jessica jaymes",
  "juicy pussy",
  "kacey jordan",
  "kagney linn karter",
  "kama sutra",
  "katie morgan",
  "kayden kross",
  "kelly wells",
  "kianna dior",
  "kiki daire",
  "kim kardashian",
  "kinky milf",
  "lap dance",
  "latin ass",
  "latina ass",
  "latina milf",
  "latina pussy",
  "latina teen",
  "lela star",
  "lesbian anal",
  "lesbian ass",
  "lesbian massage",
  "lesbian sex",
  "lesbian squirt",
  "lesbian squirting",
  "lesbian threesome",
  "lesbian xxx",
  "lexi belle",
  "lexington steele",
  "lisa ann",
  "little pussy",
  "love porn",
  "madison ivy",
  "maria ozawa",
  "marry queen",
  "massage parlor",
  "massive cock",
  "massive cumshot",
  "massive tits",
  "mature milf",
  "melissa lauren",
  "men at play",
  "micah moore",
  "milf gangbang",
  "milf lesbian",
  "milf massage",
  "milf pussy",
  "milf sex",
  "milf squirt",
  "milf threesome",
  "misty stone",
  "mom pov",
  "money talks",
  "monica santhiago",
  "monica sweetheart",
  "monique alexander",
  "monster cock",
  "mother and daughter",
  "mother and son",
  "mother daughter",
  "mother in law",
  "my first sex teacher",
  "naked beach",
  "naked girl",
  "naked yoga",
  "naomi russell",
  "natasha nice",
  "natural boobs",
  "natural porn",
  "natural tits",
  "naughty america",
  "naughty girls",
  "naughty office",
  "net video girls",
  "nice ass",
  "nice asses",
  "nikki benz",
  "nikki rhodes",
  "nina hartley",
  "nude beach",
  "nuru massage",
  "office sex",
  "oil orgy",
  "oil overload",
  "oiled tits",
  "oiled up",
  "oily massage",
  "old man",
  "open ass",
  "oral sex",
  "orgy sex",
  "outdoor blowjob",
  "outdoor sex",
  "paris hilton",
  "passed out",
  "passion hd",
  "passionate sex",
  "perfect ass",
  "perfect pussy",
  "perfect tits",
  "perky tits",
  "petite teen",
  "phat ass",
  "phoenix marie",
  "pick up",
  "pink pussy",
  "porn online",
  "pov blowjob",
  "prostate massage",
  "public disgrace",
  "public masturbation",
  "public sex",
  "pussy cum",
  "pussy fuck",
  "pussy licking",
  "pussy massage",
  "rachel roxxx",
  "rachel starr",
  "raw fuck club",
  "real porn",
  "real sex",
  "real slut party",
  "real swingers",
  "reality kings",
  "reality sex",
  "red head",
  "redhead fuck",
  "redhead milf",
  "redhead pov",
  "redhead teen",
  "reverse cowgirl",
  "reverse gangbang",
  "riding compilation",
  "riding creampie",
  "rocco siffredi",
  "ron jeremy",
  "rough anal",
  "rough deepthroat",
  "rough sex",
  "round ass",
  "ruined orgasm",
  "russian mom",
  "russian sluts",
  "russian teen",
  "ryan conner",
  "sandra romain",
  "sandy sweet",
  "sara jay",
  "sarah vandella",
  "savannah stern",
  "school girl",
  "sensual sex",
  "sex and submission",
  "sex massage",
  "sex party",
  "sex tape",
  "sex teacher",
  "sexy blonde",
  "sexy latina",
  "sexy milf",
  "shawna lenee",
  "short hair",
  "shower sex",
  "sindee jennings",
  "skinny teen",
  "sloppy blowjob",
  "softcore porn",
  "sophie dee",
  "spanish porn",
  "spring break",
  "step dad",
  "step daughter",
  "step mom",
  "step sister",
  "stormy daniels",
  "strap on",
  "sunny lane",
  "swallow compilation",
  "sweet pussy",
  "taylor rain",
  "teagan presley",
  "teen anal",
  "teen ass",
  "teen blonde",
  "teen blowjob",
  "teen casting",
  "teen fuck",
  "teen pov",
  "teen threesome",
  "threesome sex",
  "tia ling",
  "tight ass",
  "tight pussy",
  "tiny teen",
  "tiny tits",
  "titty fucking",
  "too big",
  "top porn",
  "tori black",
  "tory lane",
  "triple anal",
  "triple penetration",
  "ultimate blowjob",
  "underwear fetish",
  "up the ass",
  "upper floor",
  "vanessa lane",
  "vicky vette",
  "vivian schmitt",
  "watching porn",
  "wedding orgy",
  "wet pussy",
  "wet tits",
  "white ass",
  "wife bbc",
  "wife creampie",
  "wife swap",
  "wife xxx",
  "wild sex",
  "woodman casting",
  "wrestling sex",
  "xxx parody",
  "yoga pants",
  "young blonde",
  "young boy",
  "young brunette",
  "young cock",
  "young fuck",
  "young girl",
  "young girls",
  "young pussy",
]);

const adultPattern = new RegExp(
  `\\b(${Array.from(keywords).join("|")})\\b`,
  "i",
);

export const adultHandlers: Handler[] = [
  {
    field: "adult",
    pattern: new RegExp("\\b(XXX|xxx|Xxx)\\b"),
    transform: transforms.toBoolean(),
    remove: true,
  },
  {
    field: "adult",
    process: (title, meta, results) => {
      if (results.has("adult")) {
        return meta;
      }

      const titleLower = title.toLowerCase();

      if (adultPattern.test(titleLower)) {
        meta.value = true;
      }

      return meta;
    },
  },
];
