name: Generate coverage report

description: Generates a coverage report from a test run

runs:
  using: composite
  steps:
    - name: Get coverage baseline
      id: get-coverage-baseline
      uses: actions/cache/restore@v5
      with:
        key: coverage-baseline
        path: packages/core/util-vitest-config/coverage/compare/coverage-summary.json

    - name: Merge reports
      shell: bash
      run: pnpm turbo report

    - name: Upload coverage report
      uses: actions/upload-artifact@v7
      with:
        name: coverage-report
        path: packages/core/util-vitest-config/coverage
        retention-days: 1
        if-no-files-found: error
