name: Upload Visual Regression Report

description: Uploads the visual regression report after tests have been run

runs:
  using: composite
  steps:
    - name: Upload artefact
      uses: actions/upload-artifact@v7
      with:
        name: visual-regression-report
        path: |
          {apps,packages}/*/__vis__
        retention-days: 1
        if-no-files-found: error
