import Fuse from "@zkochan/fuse-native";
import z from "zod";

export const FuseErrorCode = z.literal([
  Fuse.EPERM,
  Fuse.ENOENT,
  Fuse.ESRCH,
  Fuse.EINTR,
  Fuse.EIO,
  Fuse.ENXIO,
  Fuse.E2BIG,
  Fuse.ENOEXEC,
  Fuse.EBADF,
  Fuse.ECHILD,
  Fuse.EAGAIN,
  Fuse.ENOMEM,
  Fuse.EACCES,
  Fuse.EFAULT,
  Fuse.ENOTBLK,
  Fuse.EBUSY,
  Fuse.EEXIST,
  Fuse.EXDEV,
  Fuse.ENODEV,
  Fuse.ENOTDIR,
  Fuse.EISDIR,
  Fuse.EINVAL,
  Fuse.ENFILE,
  Fuse.EMFILE,
  Fuse.ENOTTY,
  Fuse.ETXTBSY,
  Fuse.EFBIG,
  Fuse.ENOSPC,
  Fuse.ESPIPE,
  Fuse.EROFS,
  Fuse.EMLINK,
  Fuse.EPIPE,
  Fuse.EDOM,
  Fuse.ERANGE,
  Fuse.EDEADLK,
  Fuse.ENAMETOOLONG,
  Fuse.ENOLCK,
  Fuse.ENOSYS,
  Fuse.ENOTEMPTY,
  Fuse.ELOOP,
  Fuse.EWOULDBLOCK, // Duplicate of EAGAIN
  Fuse.ENOMSG,
  Fuse.EIDRM,
  Fuse.ECHRNG,
  Fuse.EL2NSYNC,
  Fuse.EL3HLT,
  Fuse.EL3RST,
  Fuse.ELNRNG,
  Fuse.EUNATCH,
  Fuse.ENOCSI,
  Fuse.EL2HLT,
  Fuse.EBADE,
  Fuse.EBADR,
  Fuse.EXFULL,
  Fuse.ENOANO,
  Fuse.EBADRQC,
  Fuse.EBADSLT,
  Fuse.EDEADLOCK, // Duplicate of EDEADLK
  Fuse.EBFONT,
  Fuse.ENOSTR,
  Fuse.ENODATA,
  Fuse.ETIME,
  Fuse.ENOSR,
  Fuse.ENONET,
  Fuse.ENOPKG,
  Fuse.EREMOTE,
  Fuse.ENOLINK,
  Fuse.EADV,
  Fuse.ESRMNT,
  Fuse.ECOMM,
  Fuse.EPROTO,
  Fuse.EMULTIHOP,
  Fuse.EDOTDOT,
  Fuse.EBADMSG,
  Fuse.EOVERFLOW,
  Fuse.ENOTUNIQ,
  Fuse.EBADFD,
  Fuse.EREMCHG,
  Fuse.ELIBACC,
  Fuse.ELIBBAD,
  Fuse.ELIBSCN,
  Fuse.ELIBMAX,
  Fuse.ELIBEXEC,
  Fuse.EILSEQ,
  Fuse.ERESTART,
  Fuse.ESTRPIPE,
  Fuse.EUSERS,
  Fuse.ENOTSOCK,
  Fuse.EDESTADDRREQ,
  Fuse.EMSGSIZE,
  Fuse.EPROTOTYPE,
  Fuse.ENOPROTOOPT,
  Fuse.EPROTONOSUPPORT,
  Fuse.ESOCKTNOSUPPORT,
  Fuse.EOPNOTSUPP,
  Fuse.EPFNOSUPPORT,
  Fuse.EAFNOSUPPORT,
  Fuse.EADDRINUSE,
  Fuse.EADDRNOTAVAIL,
  Fuse.ENETDOWN,
  Fuse.ENETUNREACH,
  Fuse.ENETRESET,
  Fuse.ECONNABORTED,
  Fuse.ECONNRESET,
  Fuse.ENOBUFS,
  Fuse.EISCONN,
  Fuse.ENOTCONN,
  Fuse.ESHUTDOWN,
  Fuse.ETOOMANYREFS,
  Fuse.ETIMEDOUT,
  Fuse.ECONNREFUSED,
  Fuse.EHOSTDOWN,
  Fuse.EHOSTUNREACH,
  Fuse.EALREADY,
  Fuse.EINPROGRESS,
  Fuse.ESTALE,
  Fuse.EUCLEAN,
  Fuse.ENOTNAM,
  Fuse.ENAVAIL,
  Fuse.EISNAM,
  Fuse.EREMOTEIO,
  Fuse.EDQUOT,
  Fuse.ENOMEDIUM,
  Fuse.EMEDIUMTYPE,
]);

type FuseErrorCode = z.infer<typeof FuseErrorCode>;

export class FuseError extends Error {
  errorCode: FuseErrorCode;

  constructor(errorCode: FuseErrorCode, message: string) {
    super(message);

    this.errorCode = errorCode;
  }
}

export function isFuseError(error: unknown): error is FuseError {
  return error instanceof FuseError;
}
