services:
  riven:
    container_name: riven
    build:
      context: ../..
      dockerfile: apps/riven/Dockerfile
    restart: unless-stopped
    tty: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse
    env_file: .env.riven
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      RIVEN_SETTING__vfsMountPath: /mount
      RIVEN_SETTING__redisUrl: redis://riven-cache:6379
      RIVEN_SETTING__databaseUrl: postgresql+psycopg2://postgres:${DATABASE_PASSWORD}@riven-db:5432/riven
      RIVEN_PLUGIN_SETTING__REPO_PLUGIN_SEERR__url: http://seerr:5055
      RIVEN_PLUGIN_SETTING__REPO_PLUGIN_PLEX__plexServerUrl: http://plex:32400
    volumes:
      - ./docker-data/riven:/riven/data
      - ${HOST_VFS_MOUNT_PATH}:/mount:rshared
    ports:
      - 8080:8080
    depends_on:
      riven-cache:
        condition: service_healthy
      riven-db:
        condition: service_healthy

  riven-db:
    image: postgres:17-alpine
    container_name: riven-db
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file: .env.riven-db
    volumes:
      - riven-db:/var/lib/postgresql/data/pgdata
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5

  riven-cache:
    container_name: riven-cache
    image: redis
    restart: unless-stopped
    command: redis-server --maxmemory-policy noeviction --appendonly yes
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - 6379:6379
    volumes:
      - ./docker-data/riven-cache:/data

volumes:
  riven-db:
