name: Chromatic

on:
  push:

env:
  TURBO_RUN_SUMMARY: 1
  DO_NOT_TRACK: true # Disable Turborepo telemetry - https://turborepo.dev/docs/telemetry

permissions:
  contents: read

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up project environment
        uses: ./.github/actions/set-up-project-environment

      - name: Run Chromatic
        run: pnpm turbo chromatic --continue
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          TURBO_TEAM: ${{ vars.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

      - uses: charpeni/turborepo-summary-action@v1
        if: always()
