name: Deploy Wiki to GitHub Pages

on:
  push:
    branches:
      - main
      - feat/wiki # TODO: remove after testing
    paths:
      - "apps/wiki/**"
      - "packages/plugin-*/docs/**"
      - "apps/riven/docs/**"
      - "apps/riven/lib/riven-settings.schema.ts"
      - ".github/workflows/deploy-wiki.yaml" # TODO: remove after testing

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  DO_NOT_TRACK: true

jobs:
  build:
    name: Build Wiki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up project environment
        uses: ./.github/actions/set-up-project-environment

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build wiki
        run: pnpm turbo build --filter=@repo/wiki
        env:
          TURBO_TEAM: ${{ vars.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/wiki/out

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
