name: Inspect Visual Regression Report

on:
  workflow_run:
    workflows:
      - Component Tests
    types:
      - completed
  workflow_dispatch:
    inputs:
      workflow-run-id:
        description: Workflow run ID containing the visual regression report
        required: true

jobs:
  check-for-diffs:
    name: Check for diffs
    runs-on: ubuntu-latest
    permissions:
      actions: read
    outputs:
      requires-update: ${{ steps.changes.outputs.diffs == 'true' || steps.changes.outputs.new-baselines == 'true' }}
      diffs-count: ${{ steps.changes.outputs.diffs_count }}
      new-baselines-count: ${{ steps.changes.outputs.new-baselines_count }}
      workflow-run-id: ${{ github.event.inputs.workflow-run-id || github.event.workflow_run.id }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Download visual regression report
        uses: actions/download-artifact@v8
        id: download-visual-regression-report
        with:
          name: visual-regression-report.zip
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.workflow-run-id || github.event.workflow_run.id }}

      - name: Stage files
        run: git add .

      - name: Check for visual regression diffs
        uses: dorny/paths-filter@v4
        id: changes
        with:
          base: HEAD
          filters: |
            diffs:
              - '{apps,packages}/*/__vis__/**/__diffs__/**'
            new-baselines:
              - added: '{apps,packages}/*/__vis__/**/__baselines__/**'

  post-pr-comment:
    name: Post PR comment
    needs: check-for-diffs
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: 8BitJonny/gh-get-current-pr@4.0.0
        id: pr
        with:
          sha: ${{ github.event.workflow_run.head_sha }}
          filterOutClosed: true
          filterOutDraft: true

      - name: Report visual regression diffs
        uses: mshick/add-pr-comment@v3
        if: steps.pr.outputs.number
        with:
          status: ${{ needs.check-for-diffs.outputs.requires-update == 'true' && 'failure' || 'success' }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue: ${{ steps.pr.outputs.number }}
          message-id: visual-regression-diffs
          message-failure: |
            **${{ needs.check-for-diffs.outputs.diffs-count }} visual regressions found.**
            **${{ needs.check-for-diffs.outputs.new-baselines-count }} new baselines added.**
          message-success: |
            **No visual regressions found!**

  update-baseline-snapshots:
    name: Update baseline snapshots
    needs: check-for-diffs
    if: ${{ needs.check-for-diffs.outputs.requires-update == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: update-visual-regression-baselines
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Download visual regression report
        uses: actions/download-artifact@v8
        id: download-visual-regression-report
        with:
          name: visual-regression-report.zip
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.workflow-run-id || github.event.workflow_run.id }}

      - uses: EndBug/add-and-commit@v10
        with:
          message: "chore: update visual regression baseline snapshots"
