name: PR Quality

permissions:
  contents: read
  issues: read
  pull-requests: write

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - edited

jobs:
  pr-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up project environment
        uses: ./.github/actions/set-up-project-environment

      - name: Validate PR title
        run: echo "${{ github.event.pull_request.title }}" | pnpm commitlint
        env:
          NODE_ENV: production

  anti-slop:
    runs-on: ubuntu-latest
    steps:
      - uses: peakoss/anti-slop@v0.3.0
        with:
          max-failures: 4
          failure-add-pr-labels: slop
          failure-pr-message: |
            Your PR has been flagged as potentially low-quality by our automated checks.

            See the "PR Quality" check for more details. If you believe this is a mistake, please reach out to the maintainers.
