name: Report Knip results

on:
  workflow_run:
    workflows:
      - Verify
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      checks: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          ref: main
          repository: ${{ github.event.workflow_run.pull_requests.base.repo.name }}

      - name: Set up runner
        uses: ./.github/actions/set-up-project-environment

      - name: Report Knip results
        uses: codex-/knip-reporter@v3
        with:
          command_script_name: knip:ci:production
          verbose: true
