name: Report Visual Regression results

on:
  workflow_run:
    workflows:
      - Component Tests
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      pull-requests: write
    steps:
      - name: Download visual regression report
        uses: actions/download-artifact@v8
        id: download-visual-regression-report
        with:
          name: visual-regression-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Check for visual regression diffs
        uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            diffs:
              - '{apps,packages}/*/__vis__/**/__diffs__/**'
            newBaselines:
              - added: '{apps,packages}/*/__vis__/**/__baselines__/**'

      - name: Report visual regression diffs
        uses: mshick/add-pr-comment@v3
        with:
          status: ${{ steps.changes.outputs.diffs == 'true' && 'failure' || 'success' }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-owner: ${{ github.event.workflow_run.repository.owner.login }}
          repo-name: ${{ github.event.workflow_run.repository.name }}
          message-id: visual-regression-diffs
          message-failure: |
            **${{ steps.changes.outputs.diffs_count }} visual regressions found.**
            **${{ steps.changes.outputs.newBaselines_count }} new baselines added.**
          message-success: |
            **No visual regressions found!**
