name: Validate PR Title

permissions:
  contents: read

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

jobs:
  validate-pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up project environment
        uses: ./.github/actions/set-up-project-environment

      - name: Validate PR title
        run: echo "${{ github.event.pull_request.title }}" | pnpm commitlint
