name: Verify

description: |
  This workflow runs various verification tasks (linting, type checking, tests, etc.) on pull requests.

  It also tests that the Docker images are buildable, optionally pushing to the container registry if the "build-docker" label is present.

run-name: "Verify: ${{ github.event.pull_request.title }} (#${{
  github.event.pull_request.number }})"

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: "verify-${{ github.event.pull_request.number }}"
  cancel-in-progress: true

jobs:
  verify:
    name: Verify - ${{ matrix.task.name }}
    strategy:
      fail-fast: false
      matrix:
        task:
          - name: Linting
            command: lint
            runner-requirements:
              - fuse
          - name: Types
            command: check-types
            runner-requirements:
              - fuse
          - name: Formatting
            command: format:check:ci
          - name: Tests
            command: test
            concurrency: "100%"
            runner-requirements:
              - redis-server
              - fuse
    uses: ./.github/workflows/run-turbo-task.yaml
    with:
      task: ${{ matrix.task.command }}
      concurrency: ${{ matrix.task.concurrency || '10' }}
      runner-requirements: ${{ toJson(matrix.task.runner-requirements || '[]') }}
    secrets: inherit

  migration-check:
    name: Check for missing migrations
    runs-on: ubuntu-latest
    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Check for missing migrations
        uses: ./.github/workflows/run-turbo-task.yaml
        with:
          task: migration:check
          concurrency: 1
          runner-requirements: "[]"

  build-docker-images:
    name: Build Docker Images
    needs: verify
    uses: ./.github/workflows/build-docker-images.yaml
    permissions:
      contents: read
      packages: write
    with:
      push: ${{ contains(github.event.pull_request.labels.*.name, 'build-docker') }}
    secrets: inherit
