name: Verify

run-name: "Verify PR ${{ github.event.pull_request.title }} (#${{
  github.event.pull_request.number }})"

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: "verify-${{ github.event.pull_request.number }}"
  cancel-in-progress: true

jobs:
  verify:
    name: Verify - ${{ matrix.task.name }}
    strategy:
      fail-fast: false
      matrix:
        task:
          - name: Linting
            command: lint
            runner-requirements:
              - fuse
          - name: Types
            command: check-types
            runner-requirements:
              - fuse
          - name: Formatting
            command: format:check:ci
          - name: Tests
            command: test
            concurrency: "100%"
            runner-requirements:
              - redis-server
              - fuse
    uses: ./.github/workflows/run-turbo-task.yaml
    with:
      task: ${{ matrix.task.command }}
      concurrency: ${{ matrix.task.concurrency || '10' }}
      runner-requirements: ${{ toJson(matrix.task.runner-requirements || '[]') }}
    secrets: inherit

  build-docker-images:
    name: Build Docker Images
    needs: verify
    uses: ./.github/workflows/build-docker-images.yaml
    permissions:
      contents: read
      packages: write
    with:
      push: ${{ contains(github.event.pull_request.labels.*.name, 'build-docker') }}
    secrets: inherit
