name: Post verify

description: Runs post-verification steps after a task is completed

inputs:
  task:
    description: The task that was run
    required: true

runs:
  using: composite
  steps:
    - name: Merge coverage reports
      if: ${{ inputs.task == 'test' }}
      uses: ./.github/actions/generate-coverage-report

    - name: Report Knip results in PR
      if: ${{ inputs.task == '//#knip:ci:production' && github.event.pull_request != null && github.event.pull_request.head.repo.full_name == github.repository }}
      uses: joemckie/knip-reporter@feat/run-from-existing-report
      with:
        json_report_path: knip-report.json
        verbose: true
